name: UEFITool

on: 
  push:

jobs:
  build:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory ${{runner.workspace}}/build/UEFITool && cmake -E make_directory $GITHUB_WORKSPACE/qt

    - name: Get Qt
      shell: bash
      working-directory: ${{runner.workspace}}/build/UEFITool
      run: git clone https://github.com/LongSoft/qt-5.6.3-static-x86-msvc2017

    - name: Unpack Qt
      shell: bash
      working-directory: ${{runner.workspace}}/build/UEFITool/qt-5.6.3-static-x86-msvc2017
      run: 7z x qt-5.6.3-static-x86-msvc2017.zip -o $GITHUB_WORKSPACE

    - name: Qmake
      shell: bash
      working-directory: ${{runner.workspace}}/build/UEFITool
      run: $GITHUB_WORKSPACE/qt-5.6.3-static-x86-msvc2017/bin/qmake .

    - name: Build
      working-directory: ${{runner.workspace}}/build/UEFITool
      shell: cmd
      run: | 
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          nmake release


